### ISSUE TITLE
Firebase database and Firebase auth IOS issue

### ISSUE THREAD

**Issue by Assalafi** [mrdishant/flutter_geofire#37]
Not working with latest Firebase database, Firebase auth on ios

**Comment by qasim-tuluu** [comment]
The plugin is not compatible with the latest Firebase Database, is there any hope we should expect an update?

**Comment by qasim-tuluu** [comment]
In order to get the plugin work with iOS do the following:
Add the plugin to pubspec.yaml --> flutter_geofire: 2.0.3

Add the following to podfile: 
```
target 'Runner' do
            use_frameworks!
            use_modular_headers!
            pod 'GeoFire', :git => 'https://github.com/firebase/geofire-objc'
            
            flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
            end
```

Open file flutter_geofire.podspec (ios/.symlinks/plugins/flutter_geofire/ios/flutter_geofire.podspec)
Replace the following:
**s.ios.dependency 'GeoFire', '~> 5.0'** (~> 4.0 with ~> 5.0)

**Comment by mrdishant** [comment]
Resolved in the latest version of plugin...
